export enum FormData {
  JOB = 'job',
  FIRST_NAME = 'firstName',
  LAST_NAME = 'lastName',
  EMAIL = 'email',
  PHONE = 'phone',
  COUNTRY = 'country',
  CITY = 'city',
  ADDRESS = 'address',
  DRIVING_LICENSE = 'drivingLicense',
  SUMMARY = 'summary',
  SUMMARY_TITLE = 'summaryTitle',
  PERSONAL_TITLE = 'personalTitle',
  COURSES_TITLE = 'coursesTitle',
  EDUCATION_TITLE = 'educationTitle',
  EMPLOYMENT_TITLE = 'employmentTitle',
  LANGUAGES_TITLE = 'languagesTitle',
  LINK_TITLE = 'linkTitle',
  SKILLS_TITLE = 'skillsTitle',
}
