export { default as EditableHeader } from './EditableHeader/EditableHeader';
export { default as InputsList } from './InputsList/InputsList';
export { default as EditableAccordion } from './EditableAccordion/EditableAccordion';
export { default as EditorBlock } from './DocumentEditorSection/DocumentEditorSection';
export { default as ContactDetails } from './ContactDetails/ContactDetails';
export { default as Skills } from './Skills/Skills';
export { default as DocumentPreviewPagination } from './DocumentPreviewPagination/DocumentPreviewPagination';
export { default as DocumentEditorSection } from './DocumentEditorSection/DocumentEditorSection';
export { default as SelectTemplates } from './SelectTemplate/SelectTemplate';
